
version: '3.8'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:8.0
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
      # - ./storage/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: shipping_service
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
